### ISSUE TITLE
Conflicts with tox-venv

### ISSUE THREAD

**Issue by jayvdb** [pglass/tox-pip-version#11]
tox-venv uses the same hook.

I wonder if it is possible to detect venv is active, and call it's replacement.

**Comment by pglass** [comment]
Hmm, I'm not immediately sure how to solve this.

From the [tox docs](https://tox.readthedocs.io/en/latest/plugins.html#tox.hookspecs.tox_testenv_create),

> - To add behavior but still use tox’s implementation to set up a virtualenv, implement this hook but do not return a value (or explicitly return None).
> - To override tox’s virtualenv creation, implement this hook and return a non-None value.
> 
> Note: This hook uses firstresult=True (see pluggy first result only) – hooks implementing this will be run until one returns non-None.

Some initial thoughts

1. `tox-venv` and `tox-pip-version` cannot work together without some change. Right now, both [tox-pip-version](https://github.com/pglass/tox-pip-version/blob/master/tox_pip_version/hooks.py#L21-L50) and [tox-venv](https://github.com/tox-dev/tox-venv/blob/master/src/tox_venv/hooks.py#L82-L108) return a non-None value from each of their `tox_testenv_create` hooks, so only one of the two hooks will be run.

2. For two tox plugins implementing the same hook, it's not clear which plugin's hook function is called first, or how to guarantee one is called before or after another. Pluggy does support [`tryfirst` and `trylast`](https://pluggy.readthedocs.io/en/latest/#call-time-order) options. But, if two plugins both add `tryfirst`, then we're back to the same problem - which runs first?

    - One idea, which won't work, is to use `trylast` on the tox-pip-version's `tox_testenv_create` hook. This would allow tox-venv to run first (creating the venv), but then we're back to problem (1): since tox-venv returns non-None, no further plugin hooks will be run.
    - Also, installing a version of pip _prior_ to venv creation is pointless as well. I've tested that installing a version of pip and then creating a venv doesn't influence what version of pip the virtualenv is created with (installing a version of the `virtualenv` package
   
3. An idea that might work is to change `tox-pip-version` to use the [`tox_testenv_install_deps` hook] with `tryfirst=True`. This would get tox-pip-version out of the venv creation process entirely, and then we need to ensure pip is installed _before_ any dependencies are installed, hence the `tryfirst` option. This would solve the `tox-venv` issue, but then there could be other conflicting tox plugins.

**Comment by jayvdb** [comment]
I was thinking much less sophisticated.

1. use tox/pluggy to determine `tox_venv` is enabled.
2. call its hook instead of the tox voodoo.
```py
from tox_venv.hooks import tox_testenv_create as tox_venv_create
```

**Comment by pglass** [comment]
The problem with that is, if tox-venv is installed, it's possible that tox-pip-version's hook never gets called (see point 1 in my last comment).

**Comment by jayvdb** [comment]
Right but this plugin can use tryfirst , and tox_venv probably wont ever do that as it is an optional enhancement which few people will rely on.  otoh, tox-pip-version is a feature some envs need otherwise everything blows up, so it needs to be assertive and ensure it not bypassed.
