### ISSUE TITLE
Allow upgrading to latest

### ISSUE THREAD

**Issue by jayvdb** [pglass/tox-pip-version#15]
Now that this plugin supports tox-venv, it could be used to upgrade the pip inside the venv.  See https://github.com/tox-dev/tox-venv/pull/25#issuecomment-501415890  That isnt usually required, as tox without `tox-venv` will use `virtualenv` which does this upgrade automatically.

This might also be implemented as part of 'ranges' https://github.com/pglass/tox-pip-version/issues/12 , if it uses normal specifiers which can include `>19`, which will typically cause pip to install the latest.

**Comment by pglass** [comment]
This should be addressed in #16. You can use `pip_version = pip` to install latest (equivalent to a `pip install pip`) or use `pip_version = pip>=19.1` or similar.

**Comment by jayvdb** [comment]
I think this (upgrade to latest) needs to be possible with any extra dependencies inside the venv , such as the dependency on `packaging` in the venv.

**Comment by pglass** [comment]
Yeah, please look closer at the PR. `packaging` is a dev/test dependency only.
