### ISSUE TITLE
Include tests and LICENSE in sdist

### ISSUE THREAD

**Issue by jayvdb** [pglass/tox-pip-version#9]
Also a GitHub tag hasnt been created yet for the last release.
Looking forward to packaging this for openSUSE.

**Comment by pglass** [comment]
I just updated the tags, so [v0.0.3](https://github.com/pglass/tox-pip-version/releases/tag/v0.0.3) is there now (I should really automate this bit).

I think I've got those files included in the sdist with #10. We'll get that released soon (and feel free to comment on the PR if you notice any issues).

Thank you!
